{
    parser: "babel-eslint",
    env: {
        browser: true,
        node: true,
        es6: true,
    },
    plugins: [
        "flowtype",
        "import",
    ],
    extends: [
        "plugin:flowtype/recommended",
        "plugin:import/errors",
    ],
    rules: {
        semi: 2,
        prefer-const: 2,
        no-unused-vars: [2, { argsIgnorePattern: "^_" }],
        flowtype/delimiter-dangle: [2, "always-multiline"],
        flowtype/no-dupe-keys: 2,
        flowtype/no-primitive-constructor-types: 2,
        flowtype/no-weak-types: 2,
        flowtype/object-type-delimiter: [2, "comma"],
        flowtype/require-parameter-type: [2, { excludeArrowFunctions: "expressionsOnly" }],
        flowtype/require-return-type: [2, "always", { excludeArrowFunctions: "expressionsOnly" }],
        flowtype/require-valid-file-annotation: [2, "always", { annotationStyle: "line" }],
        flowtype/semi: 2,
    },
}
