{
  parser: "babel-eslint",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  plugins: [
    "prettier",
    "flowtype",
    "import",
  ],
  extends: [
    "eslint:recommended",
    "plugin:flowtype/recommended",
    "plugin:import/errors",
    "prettier",
    "prettier/flowtype",
  ],
  rules: {
    prettier/prettier: [2, {
      trailingComma: "es5",
      semi: false,
      printWidth: 128,
    }],
    class-methods-use-this: 2,
    curly: [2, "all"],
    eqeqeq: [2, "always"],
    consistent-return: 2,
    no-eq-null: 2,
    no-extra-bind: 2,
    no-implicit-coercion: 2,
    no-param-reassign: 2,
    no-return-await: 2,
    no-unmodified-loop-condition: 2,
    yoda: [2, "never", {
      exceptRange: true,
    }],
    no-unused-vars: [2, {
      varsIgnorePattern: "^_",
      argsIgnorePattern: "^_",
    }],
    no-var: 2,
    arrow-body-style: [2, "as-needed"],
    prefer-arrow-callback: 2,
    prefer-const: 2,
    prefer-rest-params: 2,
    prefer-spread: 2,
    prefer-template: 2,
    react/prop-types: 0,
    import/named: 0,
    import/no-unresolved: 0,
    import/newline-after-import: 2,
    import/imports-first: 2,
    import/no-dynamic-require: 2,
    import/no-extraneous-dependencies: 2,
    import/no-mutable-exports: 2,
    import/no-commonjs: 2,
    import/order: [2, {
      newlines-between: "always",
    }],
    import/no-duplicates: 2,
    flowtype/no-dupe-keys: 2,
    flowtype/no-primitive-constructor-types: 2,
    flowtype/require-parameter-type: [2, { excludeArrowFunctions: true }],
    flowtype/require-return-type: [2, "always", { excludeArrowFunctions: true }],
    flowtype/require-valid-file-annotation: [2, "always", { annotationStyle: "line" }],
  },
}
